/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Hanken Grotesk', 'Segoe UI', 'sans-serif'],
        display: ['Hanken Grotesk', 'Segoe UI', 'sans-serif'],
        body: ['Hanken Grotesk', 'Segoe UI', 'sans-serif'],
      },
      colors: {
        background: '#fbf9fc',
        'tertiary-fixed-dim': '#efbd91',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#613f1e',
        'on-secondary-container': '#007349',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#000b20',
        'secondary-fixed-dim': '#50df9b',
        'on-surface-variant': '#44474d',
        'surface-tint': '#4c5f7f',
        'surface-dark': '#0A1421',
        'secondary-fixed': '#70fcb5',
        'surface-container-highest': '#e4e2e5',
        'action-blue': '#2E67D1',
        'surface-container-high': '#e9e7ea',
        'primary-fixed': '#d6e3ff',
        'inverse-on-surface': '#f2f0f3',
        'surface-variant': '#e4e2e5',
        'tertiary-container': '#361b00',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#2d1600',
        'surface-container-low': '#f5f3f6',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#002112',
        'on-error': '#ffffff',
        outline: '#74777e',
        'on-background': '#1b1b1e',
        'on-tertiary': '#ffffff',
        'on-surface': '#1b1b1e',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#344766',
        'indicator-low': '#1E88E5',
        'outline-variant': '#c4c6ce',
        surface: '#fbf9fc',
        'secondary-container': '#70fcb5',
        'inverse-primary': '#b4c7ec',
        'on-secondary-fixed-variant': '#005232',
        secondary: '#006c44',
        'on-tertiary-container': '#ac8059',
        'inverse-surface': '#303033',
        'indicator-high': '#E53935',
        'primary-container': '#0d223f',
        'surface-container': '#efedf0',
        'primary-fixed-dim': '#b4c7ec',
        'indicator-optimal': '#1EBC7C',
        tertiary: '#160800',
        'surface-bright': '#fbf9fc',
        'surface-dim': '#dbd9dc',
        'on-primary-fixed': '#051b38',
        'on-primary-container': '#778aac',
        'tertiary-fixed': '#ffdcc0',
        wellness: {
          teal: '#14b8a6',
          'teal-dark': '#0f766e',
          mint: '#ecfdf5',
        },
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
      spacing: {
        gutter: '24px',
        'section-padding': '80px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
      },
      boxShadow: {
        metric:
          '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 16px rgba(15, 118, 110, 0.06)',
        'metric-hover':
          '0 4px 12px rgba(15, 23, 42, 0.08), 0 8px 28px rgba(15, 118, 110, 0.14)',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.25rem',
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
